### ISSUE TITLE
Add necessary collections and dummy data for version 0

### ISSUE THREAD

**Issue by angelkbrown** [Code-the-Dream-School/ee-prac-team2-back#16]
In v0, we need to store activities, which hold a tally of votes and may belong to a category (type of activity).

Backend team to fill in details about data structure here.

**Comment by msrezaie** [comment]
Here is a JSON example of a single resource from the activity data model:
{
    "name": "Reading a Book",
    "category": "relaxing",
    "votes": 15,
    "description": "Enjoy a good book at home."
}

I have already saved 10 instances of such dummy data into the activity data model.

**Comment by dargaCode** [comment]
@msrezaie does each of these have an `id` as well?

**Comment by msrezaie** [comment]
Yes, in MongoDB each schema has a default _id field. The 'name' and 'category' fields are required to have values, and the 'votes' and 'description' fields are set to have default values in the data model. So while creating a new document, there is no need to include id, votes, and description fields in the JSON.

**Comment by dargaCode** [comment]
Makes sense, thank you!
