### ISSUE TITLE
Deploy to production

### ISSUE THREAD

**Issue by angelkbrown** [Code-the-Dream-School/ee-prac-team2-back#19]
- Move the `origin` defined in the CORS header to an environment variable
- Deploy `main` branch as a [Web Service](https://dashboard.render.com/web/new) in Render
- Set up the `origin` environment variable in Render

**Comment by msrezaie** [comment]
The [Main](https://github.com/Code-the-Dream-School/ee-prac-team2-back/tree/main) branch is successfully deployed on render. Here is the access live API URL:

https://date-night-4gb5.onrender.com/api/v1

**Comment by msrezaie** [comment]
The [Main](https://github.com/Code-the-Dream-School/ee-prac-team2-back/tree/main) branch is successfully deployed on render. Here is the live API's URL:

https://date-night-4gb5.onrender.com/api/v1
